### ISSUE TITLE
It doesn't seem to remove all calls

### ISSUE THREAD

**Issue by EdieLemoine** [azu/babel-plugin-strip-function-call#2]
I have a class named `Logger` with a bunch of static functions in it. I made webpack skip importing the file on production and now I'm trying to use your plugin to remove the calls to Logger from my code. However, it's not working (entirely). I have 23 calls to Logger and most are removed but there are still 3 left in my production code causing errors. I've tried tracking down which calls these are and tried to put a `NODE_ENV` condition around some but I can't get them to not show up in my production code. Do I need to do something extra if they're inside a if/else or try/catch block or something?

Here is my production webpack config: 
```js
module.exports = (env, argv) => {
  const isProd = argv.mode === 'production';
  const prodPlugins = [];
  const babelProdPlugins = [];

  if (isProd) {
  // Don't import Logger.js.
    prodPlugins.push(new webpack.IgnorePlugin({
      resourceRegExp: /helpers\/Logger$/,
    }));

    // Strip Logger and console.log calls.
    babelProdPlugins.push([
      'strip-function-call',
      {
        strip: [
          'Logger.background',
          'Logger.content',
          'Logger.error',
          'Logger.event',
          'Logger.info',
          'Logger.popup',
          'Logger.request',
          'Logger.success',
          'Logger.warning',
        ],
      },
    ]);
  }

  return {
    mode: 'production',
    entry: {
      functions: ['./src/scss/content.scss'],
      background: './src/background.js',
      content: './src/content.js',
    },
    output: {
      filename: 'js/[name].js',
    },
    plugins: [
      ...prodPlugins,
      new CopyWebpackPlugin([
        {from: 'src/images', to: 'images'},
      ]),
      new MiniCssExtractPlugin({
        filename: '[name].css',
        chunkFilename: '[id].css',
      }),
    ],
    module: {
      rules: [
        {
          test: /\.m?js$/,
          exclude: /(node_modules|bower_components)/,
          use: {
            loader: 'babel-loader',
            options: {
              presets: ['@babel/preset-env'],
              plugins: [
                ...babelProdPlugins,
                '@babel/plugin-proposal-class-properties',
                '@babel/plugin-transform-runtime',
                '@babel/plugin-transform-named-capturing-groups-regex',
              ],
            },
          },
        },
        {
          test: /\.scss$/,
          use: [
            {
              loader: 'file-loader',
              options: {
                name: 'css/[name].css',
              },
            },
            'extract-loader',
            'css-loader?-url',
            'sass-loader',
          ],
        },
      ],
    },
  };
}
```

In my production code I still see three errors like this:
```js
!function(){var e=new Error("Cannot find module '../helpers/Logger'");throw e.code="MODULE_NOT_FOUND",e}
```

Thanks in advance!

**Comment by azu** [comment]
I think that is caused by `IgnorePlugin` config.

```
    prodPlugins.push(new webpack.IgnorePlugin({
      resourceRegExp: /helpers\/Logger$/,
    }));
```

`IgnorePlugin` disallow to include `helpers/Logger`, but your code base import `'../helpers/Logger'`.
That will throw "Cannot find module" error.
`babel-plugin-strip-function-call` does not remove `import` statement or `require` function.
As a result, your code import `../helpers/Logger`, but `../helpers/Logger` does not exist.

**Comment by azu** [comment]
Another Approach: https://www.npmjs.com/package/webpack-strip-log-loader

**Comment by EdieLemoine** [comment]
My webpack config removes "dead code" as far as I know, so if Logger isn't getting called I think it should ignore/remove the import statements. Maybe I'm misunderstanding. 

I tried the package you linked and I got it to work the way I want now, thank you!
